name: chaos_crypt
description: "基于混沌理论的高性能加密演示 APP"
publish_to: "none"
version: 1.0.3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image: ^4.5.3
  file_picker: ^8.1.7
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  ffi: ^2.2.0
  shared_preferences: ^2.5.4
  receive_sharing_intent: ^1.8.1
  device_info_plus: ^12.3.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
